language: c

# Don't do CI for WIP branches
branches:
  except:
    - /^WIP-.*$/

sudo: true

install:
  - git fetch --unshallow && git fetch --tags
  - git describe
  - make conda
  - make unbind-helper || true

script:
  - make version
  - make check
  - make test || true
  - make root-test || true

